  
  import SmoothScroll from "./components/UI/SmoothScroll";
  import type { Metadata } from "next";

  import "./globals.css";





  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
   <link
          rel="preload"
          href="/HeroBG.png" // <-- CHANGE THIS if you renamed your image!
          as="image"
        />

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body>
        <SmoothScroll>
            {children}
        </SmoothScroll>
        </body>
      </html>
    );
  }
